version: "3.9"
services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ./tmp/redis:/data
    ports: 
      - 6379:6379

  api:
    container_name: api
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/instabug
    ports:
      - "3000:3000"
    environment:
            DB_USER: ${DB_USER}
            DB_NAME: ${DB_NAME}
            DB_PASSWORD: ${DB_ROOT_PASSWORD}
            DB_HOST: db
            REDIS: redis
    depends_on:
      - db