# syntax=docker/dockerfile:1
FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs
WORKDIR /instabug
COPY Gemfile /instabug/Gemfile
COPY Gemfile.lock /instabug/Gemfile.lock
RUN bundle install
