default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DB_URL'] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV['DB_URL_TEST'] %>

production:
  <<: *default
